import Mathlib.Tactic
import OctaveCoverProofs.LayerCyclicityTypes
import OctaveCoverProofs.CycleHolonomyWitness1

/-!
  ## GradedOctaveCover — the ℤ-graded cover that integrates loop + climb

  **What this file is.** `CycleHolonomyWitness1.lean` proves that the base 9-cycle is *flat*:
  every coboundary connection over it has holonomy `0`
  (`coboundary_is_flat`), while the winding generator (`fun _ => 1`, holonomy `9`) is provably
  NOT a coboundary (`spiral_not_coboundary`). That leaves an honest gap: the climb is real,
  but it lives OUTSIDE the flat base.

  This file names *where* it lives and shows the two are one object. The flat base
  (`Layer` under `transcend`, from `LayerCyclicityTypes.lean`) is the **degree-0
  face** of a ℤ-graded cover; the climb is the cover's **winding generator**. No climb is
  manufactured in the base — `transcend^9 = id` still holds, the base stays flat — but the
  cover hosts the octave climb the quotient `ℕ → Layer` threw away. This is the universal-cover
  / central-extension construction, instantiated on the proved 9-cycle.

  **The integration, in five proved facts** (`graded_octave_integration`):
  1. `proj_succ` — the covering projection `proj : ℕ → Layer` intertwines the integer
     successor `n ↦ n+1` with `transcend` (the bundle commuting square).
  2. `proj_periodic` — one full base loop is the deck transformation: `proj (n+9) = proj n`.
     The octave (`+9`) generates the deck group.
  3. `proj_surjective` + `proj_inj_fundamental` — `proj` is bijective on the fundamental
     domain `{0,…,8}`, so `Layer ≃ ℕ / 9ℕ`: **the flat base IS the degree-0 quotient.**
  4. `grade_one_loop` — the winding generator's grade increments by exactly one `OCTAVE`
     per base loop. `winding_not_coboundary` — and it is no coboundary.
  5. Non-vacuity — the cover grade observably separates climb (`OCTAVE`) from return (`0`),
     so a measured grade *means* something.

  **Honest scope.** Built on the base type `LayerCyclicityTypes.Layer` (where the flat
  result is proved). The `OctaveStructure` *class* instance elsewhere in this repository uses
  a DIFFERENT carrier (`Layer.lean`'s `Layer`, L0–L8, `Layer.next`); identifying the two bases
  is a separate isomorphism (`LayerBaseIso.lean`), NOT claimed here. This file proves the
  abstract core: a flat cyclic base is the degree-0 face of its ℤ-graded cover, and the
  winding is the non-coboundary generator. Whether a given concrete domain *forces* a real
  grade (vs. an observer merely counting loops) is a separate, per-domain question — answered
  for music and chemistry in the instance files, and answered NO for cosmology in
  `CosmoEpochsGradedCoverNegative.lean`.
-/

namespace GradedOctaveCover

open LayerCyclicityTypes
open CycleHolonomyWitness1

-- ============================================================
-- THE COVER PROJECTION  π : ℕ → Layer
-- ============================================================

/-- The forward universal-cover projection: climb `n` rungs from the basepoint `L1`
    and read off which base layer you are over. `ℕ` is the cover total space (the
    "octave-numbered" positions); `Layer` is the base 9-cycle. -/
def proj (n : ℕ) : Layer := transcend_n n Layer.L1

/-- **Bundle commuting square.** Climbing one cover rung projects to one `transcend`
    step on the base — the projection intertwines the integer successor with `transcend`. -/
theorem proj_succ (n : ℕ) : proj (n + 1) = transcend (proj n) := rfl

/-- `transcend^9 = id`: the base 9-cycle closes. (Proved locally by case analysis.) -/
theorem transcend_nine (l : Layer) : transcend_n 9 l = l := by
  cases l <;> rfl

/-- Iterated `transcend` is additive in the step count (function-iteration law). -/
theorem transcend_n_add (a b : ℕ) (l : Layer) :
    transcend_n (a + b) l = transcend_n a (transcend_n b l) := by
  induction a with
  | zero => simp [transcend_n]
  | succ k ih =>
      simp only [Nat.succ_add, transcend_n, ih]

/-- **Deck transformation = the octave.** One full base loop (`+9` in the cover) lands
    over the same base layer: `proj` is `9`-periodic, so the deck group is generated by
    the octave shift `+9`. -/
theorem proj_periodic (n : ℕ) : proj (n + 9) = proj n := by
  unfold proj
  rw [transcend_n_add, transcend_nine]

/-- Adding any number of whole octaves does not change the base position. -/
theorem proj_add_nine_mul (q r : ℕ) : proj (9 * q + r) = proj r := by
  induction q with
  | zero => simp
  | succ k ih =>
      have h : 9 * (k + 1) + r = (9 * k + r) + 9 := by ring
      rw [h, proj_periodic, ih]

/-- The base position depends only on the cover position mod 9 (the octave is invisible
    from the base). -/
theorem proj_mod (n : ℕ) : proj n = proj (n % 9) := by
  conv_lhs => rw [← Nat.div_add_mod n 9]
  rw [proj_add_nine_mul]

/-- On the fundamental domain `{0,…,8}` the cover position is recovered exactly as the
    base layer's index — the section is a genuine bijection there. -/
theorem toNat_proj (k : ℕ) (hk : k < 9) : (proj k).toNat = k := by
  interval_cases k <;> rfl

/-- **Injective on the fundamental domain.** Two cover positions below one octave that sit
    over the same base layer are equal. With `proj_mod` + `proj_surjective`, this is the
    quotient iso `Layer ≃ ℕ / 9ℕ`: the flat base is exactly the degree-0 face. -/
theorem proj_inj_fundamental (m n : ℕ) (hm : m < 9) (hn : n < 9)
    (h : proj m = proj n) : m = n := by
  have := congrArg Layer.toNat h
  rwa [toNat_proj m hm, toNat_proj n hn] at this

/-- **Surjective.** Every base layer is hit within the first octave. -/
theorem proj_surjective (l : Layer) : ∃ n, n < 9 ∧ proj n = l := by
  cases l
  · exact ⟨0, by decide, rfl⟩
  · exact ⟨1, by decide, rfl⟩
  · exact ⟨2, by decide, rfl⟩
  · exact ⟨3, by decide, rfl⟩
  · exact ⟨4, by decide, rfl⟩
  · exact ⟨5, by decide, rfl⟩
  · exact ⟨6, by decide, rfl⟩
  · exact ⟨7, by decide, rfl⟩
  · exact ⟨8, by decide, rfl⟩

-- ============================================================
-- THE GRADE  (the vertical / octave coordinate of a connection)
-- ============================================================

/-- The grade accumulated along the cover path: the running fiber sum of a connection
    `δ` over the first `k` climbed edges from `L1`. This is the cover (octave) coordinate
    induced by `δ`; `grade δ 9` is the holonomy of one base loop. -/
def grade (δ : Conn) : ℕ → ℤ
  | 0 => 0
  | k + 1 => grade δ k + δ (transcend_n k Layer.L1)

/-- The grade as an explicit prefix sum (induction-friendly normal form). -/
theorem grade_eq_range (δ : Conn) (k : ℕ) :
    grade δ k = ((List.range k).map (fun i => δ (transcend_n i Layer.L1))).sum := by
  induction k with
  | zero => simp [grade]
  | succ n ih =>
      simp only [grade, ih, List.range_succ, List.map_append, List.map_cons,
        List.map_nil, List.sum_append, List.sum_cons, List.sum_nil, add_zero]

/-- **Grade after one loop = holonomy.** The cover coordinate, read after a full base
    loop, is exactly the witness's discrete holonomy — so the holonomy lives in the grade. -/
theorem grade_nine_eq_holonomy (δ : Conn) : grade δ 9 = holonomy δ := by
  rw [grade_eq_range]
  rfl

/-- The winding generator (`+1` on every edge) climbs at unit rate in the cover. -/
theorem grade_const_one (k : ℕ) : grade (fun _ => (1 : ℤ)) k = (k : ℤ) := by
  induction k with
  | zero => rfl
  | succ n ih =>
      simp only [grade, ih]
      push_cast
      ring

/-- One octave, in cover units: a full base loop is a climb of `9`. -/
def OCTAVE : ℤ := 9

/-- **One base loop = exactly one octave.** The winding generator's grade increments by
    `OCTAVE` per period — deck-equivariance of the lift. This is the spiral, hosted in the
    cover where it belongs, with the base left flat. -/
theorem grade_one_loop (k : ℕ) :
    grade (fun _ => (1 : ℤ)) (k + 9) = grade (fun _ => (1 : ℤ)) k + OCTAVE := by
  rw [grade_const_one, grade_const_one, OCTAVE]
  push_cast
  ring

/-- The winding generator climbs exactly one octave over the base loop. -/
theorem winding_generator_climbs : grade (fun _ => (1 : ℤ)) 9 = OCTAVE := by
  rw [grade_const_one, OCTAVE]; norm_num

/-- **Degree-0 return.** Every coboundary connection (of a layer-potential)
    returns to grade `0` after a base loop — it stays in the degree-0 face.
    (`holonomy_coboundary`, transported to the cover grade.) -/
theorem coboundary_returns (g : Layer → ℤ) :
    grade (fun l => g (transcend l) - g l) 9 = 0 := by
  rw [grade_nine_eq_holonomy]
  exact holonomy_coboundary g

/-- **The climb is not a coboundary.** The winding generator is no coboundary — it cannot be
    realized in the flat base; it exists only in the cover. (= `spiral_not_coboundary`.) -/
theorem winding_not_coboundary : ¬ IsCoboundary (fun _ => (1 : ℤ)) :=
  spiral_not_coboundary

-- ============================================================
-- THE INTEGRATION (the keystone statement)
-- ============================================================

/-- **Graded-octave integration.** The flat base and the octave climb are one object:
    the base 9-cycle is the degree-0 face of a ℤ-graded cover (1–4 below), and the climb
    is that cover's winding generator — provably non-coboundary, climbing one octave per
    loop, with a non-vacuous grade that separates climb from return (5).

    Honest pairing preserved end-to-end: the base stays flat (no climb manufactured in it),
    and the climb is named exactly where it is real — upstairs in the cover. -/
theorem graded_octave_integration :
    -- (1) covering projection intertwines successor with transcend
    (∀ n, proj (n + 1) = transcend (proj n)) ∧
    -- (2) the octave (+9) is the deck transformation
    (∀ n, proj (n + 9) = proj n) ∧
    -- (3) base ≃ cover / 9ℕ : surjective + injective on the fundamental domain
    (∀ l, ∃ n, n < 9 ∧ proj n = l) ∧
    (∀ m n, m < 9 → n < 9 → proj m = proj n → m = n) ∧
    -- (4) the winding generator climbs one octave per loop and is no coboundary
    (∀ k, grade (fun _ => (1 : ℤ)) (k + 9) = grade (fun _ => (1 : ℤ)) k + OCTAVE) ∧
    ¬ IsCoboundary (fun _ => (1 : ℤ)) ∧
    -- (5) non-vacuity: grade separates climb (one octave) from return (zero)
    (grade (fun _ => (1 : ℤ)) 9 = OCTAVE) ∧
    (∀ g : Layer → ℤ, grade (fun l => g (transcend l) - g l) 9 = 0) := by
  exact ⟨proj_succ, proj_periodic, proj_surjective, proj_inj_fundamental,
    grade_one_loop, winding_not_coboundary, winding_generator_climbs, coboundary_returns⟩

end GradedOctaveCover
